### ISSUE TITLE
Integrate ledgerjs with ledger-ui

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/ledger-ui#13]

**Comment by Lyncis** [comment]
Retrieve the balance and transaction works.

When I am trying to make a transfer (from vtxdistrib to vtxtrust) I get this error:
`code: 500, message: "Internal Service Error"
error: {code: 3090003, name: "unsatisfied_authorization", what: "Provided keys, permissions, and delays do not satisfy declared authorizations"`
